#!/usr/bin/env perl

use v5.36;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use Kubectl qw( MgmtCluster Cluster1 );

Cluster1->remove("load-c1.yaml");
MgmtCluster->remove("load-mgmt.yaml");
