#!/usr/bin/env perl

use v5.36;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use Kubectl qw( MgmtCluster Cluster1 );
use Turl qw( test_GET test_NYI );

sub MAIN () {
    Cluster1->apply("load-c1.yaml");
    MgmtCluster->apply("load-mgmt.yaml");

    # Things that don't work according to doctopus
    #
    # - https://docs.solo.io/gloo-gateway
    # - https://docs.solo.io/gloo-mesh-enterprise/main/
    #
    # Standalone GG (use “main” version of docs):
    # - Retry & timeout
    # - Ext auth
    #     - OIDC
    #     - ApiKeys
    # Mesh:
    # - FailOver
    # - Ext auth
    #     - OIDC
    #     - ApiKeys

    test_GET(
        "http://www.example.com:31080/productpage",
        "Single Gateway Single Backend",
    );
    test_GET(
        "https://www.example.com:31443/productpage",
        "https listeneer",
    );
    test_NYI("https listener with file mount");
    test_NYI("SNI routing");
    test_NYI("mTLS listener");
    test_NYI("Single Gateway Multi-cluster backend (non virtual destination)");
    test_NYI("Multiple Gateway Multi cluster application (non virtual destination)");
    test_NYI("Prefix based routing");
    test_NYI("Exact path match");
    test_NYI("Header name based routing");
    test_NYI("Header value routing");
    test_NYI("Header value based regex routing");
    test_NYI("Header invert match routing");
    test_NYI("Query based routing");
    test_NYI("Query regex based routing");
    test_NYI("Method Based routing");
    test_NYI("Default Routing");
    test_NYI("Host redirect");
    test_NYI("Path redirect");
    test_NYI("Prefix rewrite redirect");
    test_NYI("Redirect with 307");
    test_NYI("HTTPS redirect");
    test_NYI("Redirect and strip query");
    test_NYI("Host Based Delegation");
    test_NYI("Path Based Delegation");
    test_NYI("3 Tier Delegation");
    test_NYI("Route to external service");
    test_NYI("Route to external service with many external endpoints");
    test_NYI("Route to external service with https upgrade");
    test_NYI("Route to an https external service no upgrade");
    test_NYI("Route to VirtualDestination");
    test_NYI("Route to virtual destination with multiple ports");
    test_NYI("Route based on subset value");
    test_NYI("Multi cluster subset routing");
}

MAIN;
