#!/usr/bin/env perl

use v5.36;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib";

use Kubectl qw( Cluster1 MgmtCluster );
use Turl qw( test_GET );
use Cert qw( make_tls_secret_if_needed );

sub MAIN () {
    Cluster1->apply("load-c1.yaml");
    MgmtCluster->apply("load-mgmt.yaml");

    make_tls_secret_if_needed({
        cluster   => Cluster1,
        name      => 'example-secret',
        host      => 'www.example.com',
        namespace => 'istio-gateway-ns',
    });

    make_tls_secret_if_needed({
        cluster   => Cluster1,
        name      => 'auth-secret',
        host      => 'auth.example.com',
        namespace => 'istio-gateway-ns',
    });

    test_GET(
        "https://www.example.com:31443/noauth",
        "noauth is ok",
        {
            headers => [ stupid => 'blubber' ],
        }
    );

    test_GET(
        "https://www.example.com:31443/auth",
        "httpbin is forbidden",
        {
            expected_status => 403,
            headers => [ stupid => 'flubber' ],
        },
    );

    test_GET(
        "https://auth.example.com:31443/realms/master",
        "keycloak is running and accessible",
    );
}

MAIN;