---
kind: WorkspaceSettings
apiVersion: admin.gloo.solo.io/v2
metadata:
  name: anything
  namespace: helloworld
spec:
  options:
    eastWestGateways:
      - selector:
          labels:
            istio: eastwestgateway
---
apiVersion: networking.gloo.solo.io/v2
kind: ExternalService
metadata:
  name: helloworld
  namespace: helloworld
spec:
  addresses:
    - "10.96.135.29"
  ports:
    - name: http
      number: 5000
      protocol: HTTP