#!/usr/bin/env perl

use v5.36;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib";

use Kubectl qw( MgmtCluster Cluster1 );
use Turl qw( test_GET test_NYI );

sub MAIN () {
    Cluster1->apply("load-c1.yaml");
    MgmtCluster->apply("load-mgmt.yaml");

    # Things that don't work according to doctopus
    #
    # - https://docs.solo.io/gloo-gateway
    # - https://docs.solo.io/gloo-mesh-enterprise/main/
    #
    # Standalone GG (use “main” version of docs):
    # - Retry & timeout
    # - Ext auth
    #     - OIDC
    #     - ApiKeys
    # Mesh:
    # - FailOver
    # - Ext auth
    #     - OIDC
    #     - ApiKeys
}

MAIN;
