---
kind: WorkspaceSettings
apiVersion: admin.gloo.solo.io/v2
metadata:
  name: anything
  namespace: httpbin
spec:
  options:
    eastWestGateways:
      - selector:
          labels:
            istio: eastwestgateway
---
kind: RouteTable
apiVersion: networking.gloo.solo.io/v2
metadata:
  name: httpbin-north-south
  namespace: httpbin
  labels:
    workspace.solo.io/exported: "true"
spec:
  hosts:
    - www.example.com
  virtualGateways:
    - name: north-south-gw
      namespace: istio-gateway-ns
      cluster: cluster-1
  http:
    - name: ratings
      labels:
        route: ratings
      matchers:
        - uri:
            prefix: /ratings
      forwardTo:
        destinations:
          - ref:
              name: ratings
              namespace: bookinfo
              cluster: cluster-1
            port:
              number: 9080
    - name: httpbin
      labels:
        auth: required
      matchers:
        - uri:
            prefix: /httpbin
      forwardTo:
        pathRewrite: /headers
        destinations:
          - ref:
              name: httpbin
              namespace: httpbin
              cluster: cluster-1
            port:
              number: 8000
---
apiVersion: admin.gloo.solo.io/v2
kind: ExtAuthServer
metadata:
  name: default-server
  namespace: httpbin
spec:
  destinationServer:
    port:
      number: 8083
    ref:
      cluster: cluster-1
      name: ext-auth-service
      namespace: gloo-mesh-addons
---
apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: oidc
  namespace: httpbin
spec:
  applyToDestinations:
    - kind: SERVICE
      selector:
        name: httpbin
        namespace: httpbin
        cluster: cluster-1
  config:
    glooAuth:
      configs:
        - basicAuth:
            apr:
              users:
                user:
                  hashedPassword: 8BvzLUO9IfGPGGsPnAgSu1
                  salt: TYiryv0/
    server:
      name: default-server
      namespace: httpbin
      cluster: cluster-1
---
kind: VirtualGateway
apiVersion: networking.gloo.solo.io/v2
metadata:
  name: north-south-gw
  namespace: istio-gateway-ns
spec:
  workloads:
    - selector:
        labels:
          istio: ingressgateway
        cluster: cluster-1
  listeners:
    - port:
        number: 80
      http: {}
    - port:
        number: 443
      http: {}
      tls:
        mode: SIMPLE
        secretName: example-secret