#!/usr/bin/env perl

use v5.36;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use Kubectl qw( MgmtCluster Cluster1 Cluster2 );

Cluster2->remove("load-c2.yaml");
Cluster1->remove("load-c1.yaml");
Cluster1->remove({
    kind      => 'secret',
    namespace => 'istio-gateway-ns',
    name      => 'example-secret',
});
Cluster1->remove({
    kind      => 'secret',
    namespace => 'istio-gateway-ew',
    name      => 'internal-secret',
});
MgmtCluster->remove("load-mgmt.yaml");

